name: Discord notification

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  notification:

    runs-on: ubuntu-latest

    steps:

      - name: Set output
        id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: "GitHub Actions"
          avatar-url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
          title: ""
          description: "v**${{ steps.vars.outputs.tag }}** has been released.\nhttps://github.com/Solor/ci_test/releases/download/${{ steps.vars.outputs.tag }}/ci_test-${{ steps.vars.outputs.tag }}.zip"
          include-details: "false"
          color-success: "#4287f5"
