name: Discord notification

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'A new version {{ EVENT_PAYLOAD.repository.full_name }} has been released.'
