name: Package and build beta/alpha versions

on:
  push:
    tags:
      - "*.*.*-*"

jobs:

  release:

    runs-on: ubuntu-latest

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Clone project
        uses: actions/checkout@v1
        with:
          fetch-depth: 50

      - name: Package and release
        uses: BigWigsMods/packager@master
        with:
          args: release.sh

