# name: Release

# on:
#   push:
#     branches:
#       - develop
#     tags:
#       - 'v*'

# jobs:
#   build:
#     name: Create Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: $PREVIOUS_TAG
#           release_name: $PREVIOUS_TAG
#           body: |
#             ## What’s Changed

#             $CHANGES
#           draft: false
#           prerelease: false


name: "tagged-release"

on:
  push:
    tags:        
      - '*'
    branches:
      - "develop"

jobs:
  pre-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
